# Generated by Django 3.1.2 on 2020-11-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Producto',
        ),
    ]
